name: workflow to push docker images to ecr

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  Images2ECR:
    runs-on: self-hosted

    steps: 

      - name: checkout code
        uses: actions/checkout@v1

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1
      - name: ecr login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: build and push docker images to ecr
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: myrepo
          IMAGE_TAG: myrepo_image

        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


